### ISSUE TITLE
Error:(29, 5) error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by pateelhs** [hypertrack/uber_for_x_android#1]
Error:(29, 5) error: method does not override or implement a method from a supertype

**Comment by poonam-hypertrack** [comment]
Please comment the method/ code.
We will add a new library version with those method/s.

**Comment by KaipraDevs** [comment]
Hello Poonam,
This is the error method- 
-@Override
    public int getSourcePlaceMarkerIconForActionID(Context mContext, String actionID) {
        return R.drawable.iconsource_marker;
    }
This is in -com/hypertrack/uber_consumer/base/MyHyperTrackMapAdapter.java	
Please define method for it..

The pusblished code also have following errors:-
 -error: cannot find symbol method showBackArrow(boolean)	
-error: cannot find symbol method setShowCurrentLocation(boolean)	
-error: cannot find symbol method setShowCurrentLocation(boolean)	
   Hope You will Update it.

**Comment by anshudwibhashi** [comment]
I had this issue too. Update to the latest Hypertrack version 0.7.39 and it will be fixed.
I had these bugs too. The way Firebase and Hypertrack have their dependencies makes dependency-version-conflicts especially tricky to fix.

I just fixed this, and made a pull-request. As soon as Hypertrack accepts it, the bugs will be fixed!

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
