### ISSUE TITLE
not working The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[15.0.0,15.0.0], 

### ISSUE THREAD

**Issue by saikat701** [hypertrack/uber_for_x_android#11]
The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[15.0.0,15.0.0], blah blah..
please any1 who succed to buid share latest android project or  apk file
It will be very help full
please

**Comment by RendaniN** [comment]
I have this problem too did you manage to solve it?

**Comment by saikat701** [comment]
do not change or replace any latest version of dependencies [its mismatch] on app-build.gradle
[firebase version on gms version ]

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
