### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ph4t0o0o0om** [hypertrack/uber_for_x_android#13]
Hey can anyone tell me about this. I clone the repo and check the pull request and apply that. But my customer app and driver app has no connection. Even if my driver app is open the customer app is keep on toasting the "no cars available" can anyone help me please.

**Comment by vijendrapatidar** [comment]
E/uberx_consumer: Error::  403: {"detail":"Invalid token."}

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
