### ISSUE TITLE
Consumer App stucks after adding destination

### ISSUE THREAD

**Issue by naumanshafique** [hypertrack/uber_for_x_android#17]
Can anyone help me how to fix this error? The consumer app is stuck on this (to view picture please click the link) https://imgur.com/RbUKL53 . Please help me badly need help. Thank you so very much!

@anshudwibhashi @abhishekpoddar24 @poonam-hypertrack

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
