### ISSUE TITLE
Android X and com.hypertrack:android:0.7.39@aar library conflicting each other

### ISSUE THREAD

**Issue by rameshkec85** [hypertrack/uber_for_x_android#20]
Getting issue when I am targeting to latest version (Android X)
/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:4703: error: duplicate value for resource 'attr/cornerRadius' with config ''.

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
