### ISSUE TITLE
starting trip 

### ISSUE THREAD

**Issue by kosekaku** [hypertrack/uber_for_x_android#25]
Hello, I have a problem. After clicking on the get directions,  I get this `error`
```
Calling startActivity() from outside of an Activity  context requires the  
FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
```
I understand we can use `addFlags(Intent.FLAG_ACTIVITY_NEW_TASK` to get around the error, however, I needed the activity to be on the same page so that I can start a ride.  because of such, there's no way the driver can start a ride.

How can I resolve such error, am on the latest app update

**Comment by deniszpua** [comment]
@itsUk45 Thanks for spotting the bug!
The flag you've mentioned doesn't affect application flow (I've attached a gif to PR to show the usecase).

**Comment by itsUk45** [comment]
@deniszpua  thanks, 
However; The app ends up at the Google maps app without a way of returning back to the previous activity such that the driver can now start a ride from the rider's pickup point to the drop-off point.  Can you kindly let me know a way around that?
