### ISSUE TITLE
Method cannot be resolved? Please help

### ISSUE THREAD

**Issue by chrismuiruriz** [hypertrack/uber_for_x_android#6]
\activities\GenerateRideActivity.java
Error:(149, 30) error: cannot find symbol method showBackArrow(boolean)
Error:(153, 34) error: cannot find symbol method setShowCurrentLocation(boolean)
Error:(157, 34) error: cannot find symbol method setShowCurrentLocation(boolean)

**Comment by chrismuiruriz** [comment]
Where are these methods?

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
