### ISSUE TITLE
Method errors

### ISSUE THREAD

**Issue by KaipraDevs** [hypertrack/uber_for_x_android#7]
Error:(29, 5) error: method does not override or implement a method from a supertype

 
-@override
public int getSourcePlaceMarkerIconForActionID(Context mContext, String actionID) {
return R.drawable.iconsource_marker;
}
This is in -com/hypertrack/uber_consumer/base/MyHyperTrackMapAdapter.java
Please define method for it..

The pusblished code also have following errors:-
-error: cannot find symbol method showBackArrow(boolean)
-error: cannot find symbol method setShowCurrentLocation(boolean)
-error: cannot find symbol method setShowCurrentLocation(boolean)
Hope You will Update it.

**Comment by anshudwibhashi** [comment]
Updating the HyperTrack SDK to the latest version fixed it for me. However, it did give rise to *many* other versioning issues with Firebase. This issue needs fixing as soon as possible!

**Comment by anshudwibhashi** [comment]
Update: I fixed the issue and just made a pull-request!

**Comment by KaipraDevs** [comment]
Thank You very much sir..I appriciate that...Thank You..

**Comment by ph4t0o0o0om** [comment]
HI GOOD DAY!! CAN SOMEONE HELP ME HOW TO IMPLEMENT THE APPLICATION? PLEASE PLEASE. I FOLLOW THE STEPS BUT I CAN'T IMPLEMENT THE APP CORRECTLY PLS HELP ME.

**Comment by ph4t0o0o0om** [comment]
@anshudwibhashi HELP ME PLS

**Comment by Sai-Adarsh** [comment]
> Update: I fixed the issue and just made a pull-request!

Could i get the code, to : saiadarshsivakumar@gmail.com

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
